image: ruby:2.4

pages:
  stage: deploy
  script:
    - sh install.sh
    - sh build.sh
    - npm install
    - npx webpack
    - gem install bundler
    - bundle install
    - rackula generate -o public -p assets
  artifacts:
    paths:
      - public
  only:
    - deployed
