stages:
  - test-firefox
  - test-chrome
  - deploy

pages:
  image: ruby:2.6.3
  stage: deploy
  script:
    - apt update
    - apt install npm -y
    - touch lib/mode-assembly_riscv.js
    - /bin/bash install.sh
    - /bin/bash build.sh
    - npm install
    - npx webpack
    - gem install bundler
    - bundle install
    - rackula generate -o public -p assets
  artifacts:
    paths:
      - public
  only:
    - deployed

test-chrome:
  stage: test-chrome
  image: node:latest
  services:
    - selenium/standalone-chrome:latest
  variables:
    RACK_ENV: "test"
    SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub"
    GITLAB_CI: "true"
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --prefer-offline
  script:
    - npm run test

test-firefox:
  stage: test-firefox
  image: node:latest
  services:
    - selenium/standalone-firefox:latest
  variables:
    RACK_ENV: "test"
    SELENIUM_FIREFOX_URL: "http://selenium__standalone-firefox:4444/wd/hub"
    GITLAB_CI: "true"
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --prefer-offline
  script:
    - npm run test
