stages:
  - test
  - deploy

services:
  - selenium/standalone-chrome:latest

variables:
  RACK_ENV: "test"
  SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub"
  GITLAB_CI: "true"

pages:
  image: ruby:2.4
  stage: deploy
  script:
    - sh install.sh
    - sh build.sh
    - npm install
    - npx webpack
    - gem install bundler
    - bundle install
    - rackula generate -o public -p assets
  artifacts:
    paths:
      - public
  only:
    - deployed

tests:
  stage: test
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install --prefer-offline
  script:
    - npm run test
